let ovn3 = angular.module("ovn3", []);
ovn3.controller("nameCtrl", function ($scope) {
    $scope.currentFilter = "";
    $scope.names = [
        "Adele George",
        "Aisha Mccray",
        "Angela Isabel Hill",
        "Barbra Lyons",
        "Berta Duffy",
        "Beulah Holloway",
        "Brittney Kitty Todd",
        "Candy Peters",
        "Carmela Alexandria Reed",
        "Cathryn Price",
        "Chelsea Debra Santana",
        "Christie Sofia Medina",
        "Claire Lessie Whitaker",
        "Claudia Paula Rivas",
        "Eileen Krista Murphy",
        "Elisa Cassie Bray",
        "Emma Gay",
        "Erica Alston",
        "Esperanza Liz Mcconnell",
        "Ester Claudine Henson",
        "Esther Ana Gaines",
        "Glenna Sarah Charles",
        "Gracie Hill",
        "Gwendolyn Misty Guy",
        "Hester Haynes",
        "Ivy Mcmillan",
        "Joann Collier",
        "Joanna Eula Price",
        "Joanna Stella Edwards",
        "Josie Bailey",
        "Kathryn Lavonne Rosales",
        "Lana Tori Reyes",
        "Latoya Shelly Bowman",
        "Lillian Collier",
        "Lucy Nona Love",
        "Marsha Mathews",
        "Maryanne Whitaker",
        "Maryellen Middleton",
        "Meghan Harrington",
        "Patrica Jana Willis",
        "Pearlie Alisha Murray",
        "Rosalie Margery Turner",
        "Rosie Frank",
        "Sharron Veronica Bruce",
        "Sonja Merritt",
        "Suzanne Harriett Sykes",
        "Tanisha Chapman",
        "Tara Gordon",
        "Tonya Christian",
        "Wendi Nannie Ward"
    ];
});